apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wave-demo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Pebintk/argocd-lab.git
    targetRevision: HEAD
    path: apps/wave-demo
  destination:
    server: https://kubernetes.default.svc
    namespace: wave-demo
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true